"""Generate the browser's platform definitions from Arcade's single JSON source."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    data = json.loads((ROOT / 'data/platforms.json').read_text(encoding='utf-8'))
    return '''// Generated by tools/build_platforms.py; edit data/platforms.json.
(function(root) {
  const definitions = %s;
  const libraries = definitions.libraries;
  const collection = value => {
    if (value?.platform_id) return libraries[value.platform_id] ? value.platform_id : '';
    return Object.keys(libraries).find(key => libraries[key].adapters.includes(value?.adapter || '')) || '';
  };
  const game = value => Object.keys(libraries).find(key => libraries[key].types.includes(value?.type)) || '';
  const searchLabel = value => {
    const key = game(value);
    if (key === 'game-boy') return definitions.search[value.platform]?.label || ({GB:'Game Boy', GBC:'Game Boy Color', GBA:'Game Boy Advance'}[value.system]) || 'Game Boy';
    return libraries[key]?.metadataScope === 'version' ? (definitions.search[value.platform]?.label || value.system || 'Unspecified platform') : (libraries[key]?.label || 'Unsupported platform');
  };
  root.ArcadePlatforms = Object.freeze({libraries, search:definitions.search, collection, game, searchLabel});
})(globalThis);
''' % json.dumps(data, ensure_ascii=False, indent=2)


if __name__ == '__main__':
    (ROOT / 'web/platforms.js').write_text(render(), encoding='utf-8', newline='\n')
