// Generated by tools/build_platforms.py; edit data/platforms.json.
(function(root) {
  const definitions = {
  "libraries": {
    "zx-spectrum": {
      "label": "ZX Spectrum",
      "adapters": [
        "spectrum-metadata-v1"
      ],
      "types": [
        "Official",
        "Homebrew",
        "Homebrew & Scene",
        "Scene",
        "ZX Spectrum",
        "Spectrum"
      ],
      "icon": "assets/platforms/portal-zx-spectrum.svg",
      "emulators": [
        "generic",
        "eightyone",
        "spectaculator"
      ],
      "targetKind": "media-file",
      "metadataScope": "folder",
      "poks": true,
      "presentationOverrides": false
    },
    "scummvm": {
      "label": "ScummVM",
      "adapters": [
        "scummvm-config-v1"
      ],
      "types": [
        "ScummVM"
      ],
      "icon": "assets/scummvm/scummvm-icon.png",
      "emulators": [
        "scummvm"
      ],
      "targetKind": "scummvm-game",
      "metadataScope": "version",
      "poks": false,
      "presentationOverrides": true
    },
    "atari-st": {
      "label": "Atari ST",
      "adapters": [
        "atari-st-disks-v1"
      ],
      "types": [
        "Atari ST"
      ],
      "icon": "assets/platforms/portal-atari-st.svg",
      "emulators": [
        "steem",
        "hatari"
      ],
      "targetKind": "disk-set",
      "metadataScope": "folder",
      "poks": false,
      "presentationOverrides": true
    },
    "game-boy": {
      "label": "Game Boy",
      "adapters": [
        "gameboy-cartridges-v1"
      ],
      "types": [
        "Game Boy"
      ],
      "icon": "assets/platforms/game-boy.svg",
      "emulators": [
        "generic"
      ],
      "targetKind": "media-file",
      "metadataScope": "folder",
      "poks": false,
      "presentationOverrides": false,
      "metadataWritable": true
    }
  },
  "search": {
    "all": {
      "label": "All platforms",
      "screenscraper": "",
      "thegamesdb": ""
    },
    "game-boy": {
      "label": "Game Boy",
      "screenscraper": "9",
      "thegamesdb": "4"
    },
    "game-boy-color": {
      "label": "Game Boy Color",
      "screenscraper": "10",
      "thegamesdb": "41"
    },
    "game-boy-advance": {
      "label": "Game Boy Advance",
      "screenscraper": "12",
      "thegamesdb": "5"
    },
    "zx-spectrum": {
      "label": "ZX Spectrum",
      "screenscraper": "76",
      "thegamesdb": "4913"
    },
    "atari-st": {
      "label": "Atari ST",
      "screenscraper": "42",
      "thegamesdb": "4937"
    },
    "amiga": {
      "label": "Amiga",
      "screenscraper": "64",
      "thegamesdb": "4911"
    },
    "dos": {
      "label": "PC DOS",
      "screenscraper": "135",
      "thegamesdb": "1"
    },
    "windows": {
      "label": "PC Windows",
      "screenscraper": "138",
      "thegamesdb": "1"
    },
    "macintosh": {
      "label": "Macintosh",
      "screenscraper": "146",
      "thegamesdb": "37"
    },
    "fm-towns": {
      "label": "FM Towns",
      "screenscraper": "253",
      "thegamesdb": "4932"
    },
    "scummvm": {
      "label": "ScummVM",
      "screenscraper": "123"
    }
  }
};
  const libraries = definitions.libraries;
  const collection = value => {
    if (value?.platform_id) return libraries[value.platform_id] ? value.platform_id : '';
    return Object.keys(libraries).find(key => libraries[key].adapters.includes(value?.adapter || '')) || '';
  };
  const game = value => Object.keys(libraries).find(key => libraries[key].types.includes(value?.type)) || '';
  const searchLabel = value => {
    const key = game(value);
    if (key === 'game-boy') return definitions.search[value.platform]?.label || ({GB:'Game Boy', GBC:'Game Boy Color', GBA:'Game Boy Advance'}[value.system]) || 'Game Boy';
    return libraries[key]?.metadataScope === 'version' ? (definitions.search[value.platform]?.label || value.system || 'Unspecified platform') : (libraries[key]?.label || 'Unsupported platform');
  };
  root.ArcadePlatforms = Object.freeze({libraries, search:definitions.search, collection, game, searchLabel});
})(globalThis);
