#!/usr/bin/env python3
"""Validate component manifests and generate Nexus's direct-file registry."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path, PurePosixPath


COMPONENTS = ("Portal", "Widgets", "Arcade", "Relay", "Host", "Nexus")
IDS = tuple(name.lower() for name in COMPONENTS)
SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
SAFE_RELATIVE = re.compile(r"^[A-Za-z0-9._/-]+$")
ALLOWED_KINDS = {"page", "catalogue", "extension", "native-service"}
ALLOWED_ACCENTS = {"violet", "cyan", "orange", "blue", "green", "pink"}


def safe_relative(value: object, *, nullable: bool = False) -> str | None:
    if value is None and nullable:
        return None
    text = str(value or "")
    path = PurePosixPath(text)
    if not text or not SAFE_RELATIVE.fullmatch(text) or path.is_absolute() or ".." in path.parts:
        raise ValueError(f"Unsafe component-relative path: {text!r}")
    return text


def load_manifests(repo: Path) -> list[dict]:
    manifests = []
    for directory, expected_id in zip(COMPONENTS, IDS):
        path = repo / directory / "component.json"
        manifest = json.loads(path.read_text(encoding="utf-8"))
        if set(manifest) != {"schemaVersion", "id", "name", "version", "kind", "entrypoint", "icon", "summary", "documents", "capabilities", "protocols", "schemas", "nexus"}:
            raise ValueError(f"{directory} manifest fields do not match schema 1")
        if manifest["schemaVersion"] != 1 or manifest["id"] != expected_id:
            raise ValueError(f"{directory} manifest identity is invalid")
        if not SEMVER.fullmatch(str(manifest["version"])):
            raise ValueError(f"{directory} manifest version is invalid")
        if manifest["kind"] not in ALLOWED_KINDS:
            raise ValueError(f"{directory} manifest kind is invalid")
        entrypoint = safe_relative(manifest["entrypoint"], nullable=True)
        icon = safe_relative(manifest["icon"])
        if entrypoint and not (repo / directory / entrypoint).is_file():
            raise ValueError(f"{directory} entrypoint does not exist: {entrypoint}")
        if not (repo / directory / icon).is_file():
            raise ValueError(f"{directory} icon does not exist: {icon}")
        documents = manifest.get("documents")
        if not isinstance(documents, dict) or set(documents) != {"todo", "changelog"}:
            raise ValueError(f"{directory} document declarations are invalid")
        for relative in documents.values():
            safe_relative(relative)
            if not (repo / directory / relative).is_file():
                raise ValueError(f"{directory} document does not exist: {relative}")
        capabilities = manifest.get("capabilities")
        if not isinstance(capabilities, list) or capabilities != sorted(set(capabilities)):
            raise ValueError(f"{directory} capabilities must be unique and sorted")
        for mapping_name in ("protocols", "schemas"):
            mapping = manifest.get(mapping_name)
            if not isinstance(mapping, dict) or any(not isinstance(value, int) or isinstance(value, bool) or value < 1 for value in mapping.values()):
                raise ValueError(f"{directory} {mapping_name} declarations are invalid")
        nexus = manifest.get("nexus")
        if not isinstance(nexus, dict) or set(nexus) != {"accent", "adapter"} or nexus["accent"] not in ALLOWED_ACCENTS or nexus["adapter"] != expected_id:
            raise ValueError(f"{directory} Nexus declaration is invalid")
        manifests.append(manifest)
    return manifests


def nexus_record(manifest: dict) -> dict:
    component = manifest["id"]
    prefix = "" if component == "nexus" else f"../{component.capitalize()}/"
    return {
        "id": component,
        "name": manifest["name"],
        "version": manifest["version"],
        "kind": manifest["kind"],
        "accent": manifest["nexus"]["accent"],
        "adapter": manifest["nexus"]["adapter"],
        "page": f"{prefix}{manifest['entrypoint']}" if manifest["entrypoint"] else None,
        "icon": f"{prefix}{manifest['icon']}",
        "summary": manifest["summary"],
        "todo": f"{prefix}{manifest['documents']['todo']}",
        "changelog": f"{prefix}{manifest['documents']['changelog']}",
        "capabilities": manifest["capabilities"],
        "protocols": manifest["protocols"],
        "schemas": manifest["schemas"]
    }


def render_registry(manifests: list[dict]) -> str:
    records = [nexus_record(manifest) for manifest in manifests]
    payload = json.dumps(records, indent=2, ensure_ascii=False)
    return "// Generated by tools/build_component_registry.py; do not edit manually.\n" + \
        "globalThis.CyruneComponentRegistry = (() => {\n" + \
        "  const deepFreeze = value => {\n    if (value && typeof value === 'object') {\n" + \
        "      Object.values(value).forEach(deepFreeze);\n      Object.freeze(value);\n    }\n    return value;\n  };\n" + \
        "  return deepFreeze({ schemaVersion: 1, components: " + payload + " });\n})();\n" + \
        "if (typeof module === 'object' && module.exports) module.exports = globalThis.CyruneComponentRegistry;\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = args.repo.resolve()
    output = repo / "Nexus" / "source" / "component-registry.js"
    rendered = render_registry(load_manifests(repo))
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            raise SystemExit("Generated Nexus component registry is out of date")
        return 0
    output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
